### ISSUE TITLE
Layout issue on Chrome

### ISSUE THREAD

**Issue by tomchadwin** [chriswhong/nyc-civic-jobs#1]
- click on eg the tech category
- hover over the first job entry in the list

More details are revealed, which overlap the subsequent search results (Chrome/Win7x64)

![2018-11-13 15_02_34-nyc civic jobs](https://user-images.githubusercontent.com/7840213/48421880-4c1cea80-e755-11e8-9d8c-dbce648e9c88.png)

**Comment by chriswhong** [comment]
Eeek, thanks for reporting... searched far and wide for a "show more" react component, but none seem to be very popular or well supported.  I'll probably have to do this on my own.

**Comment by chriswhong** [comment]
I have observed this a couple of times but can't consistently replicate it.  (both views are working as expected now for me in chrome 70.0.3538.77 on Mac

**Comment by tomchadwin** [comment]
Tried to confirm Chrome version, but just opening the About menu triggers an update. On same build as you now, and problem has gone after a Chrome restart. Sorry for the noise.
