### ISSUE TITLE
Encoding glitch

### ISSUE THREAD

**Issue by tomchadwin** [chriswhong/nyc-civic-jobs#3]
You might not have control over poorly encoded data sources, but Chrome/Win x64 is giving me some encoding artefacts:

![2018-11-13 16_54_12-nyc civic jobs](https://user-images.githubusercontent.com/7840213/48429351-db7dca00-e764-11e8-9a91-fd099e58f85c.png)

**Comment by chriswhong** [comment]
Fixed in 7f578b9ad2d355e62086142ee8424fcc19cdcfde
